{
    /* <footer>
    <nav class="left">
        <ul class="left">
            <li><a href="#">Contact</a></li>
            <li><a href='#'><img height="20px" src="styles/instagram.svg"></a></li>
        </ul>
    </nav>
        <img class="logo" src="styles/medium-size.svg">
    <nav class="rightB">
        <ul class="rightB">
            <li><a href='#'>Allergen chart</a></li>
            <li><a href='#'>Accessibility policy</a></li>
        </ul>
    </nav>
    </footer> */
}

//the above code is gonna be generated by this IFFE

const footerGenerator = (function() {
    const content = document.querySelector('#content');

    const footer = document.createElement('footer');

    const navLeft = document.createElement('nav');
    navLeft.classList.add("left");

    const ulLeft = document.createElement('ul');
    ulLeft.classList.add("left");

    const li1Bot = document.createElement('li');
    const a1Bot = document.createElement('a');
    a1Bot.href = "#";
    a1Bot.innerHTML = "Contact";
    li1Bot.appendChild(a1Bot);

    const li2Bot = document.createElement('li');
    const a2Bot = document.createElement('a');
    a2Bot.href = "#";
    const insta = document.createElement('img');
    insta.src = "../../../dist/styles/img/insta.svg";
    insta.classList.add('insta');
    a2Bot.appendChild(insta);
    li2Bot.appendChild(a2Bot);

    ulLeft.appendChild(li1Bot);
    ulLeft.appendChild(li2Bot);

    navLeft.appendChild(ulLeft);

    const logoBot = document.createElement('img');
    logoBot.src = "../../../dist/styles/img/medium-size.svg";
    logoBot.classList.add("logo");

    const navRight = document.createElement('nav');
    navRight.classList.add("rightB");

    const ulRight = document.createElement('ul');
    ulRight.classList.add("rightB");

    const li3Bot = document.createElement('li');
    const a3Bot = document.createElement('a');
    a3Bot.href = "#";
    a3Bot.innerHTML = "Allergen chart";
    li3Bot.appendChild(a3Bot);

    const li4Bot = document.createElement('li');
    const a4Bot = document.createElement('a');
    a4Bot.href = "#";
    a4Bot.innerHTML = "Accessibility policy";
    li4Bot.appendChild(a4Bot);

    ulRight.appendChild(li3Bot);
    ulRight.appendChild(li4Bot);

    navRight.appendChild(ulRight);

    footer.appendChild(navLeft);
    footer.appendChild(logoBot);
    footer.appendChild(navRight);

    content.appendChild(footer);

    return content
})();

// export {
//     footerGenerator
// }